#!/usr/bin/env bash

#check if nigxx is installed
if ! command -v nginx &> /dev/null
then
    echo "Nginx is not installed. Installing..."
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# configure firewell to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# create a webpage for 404
echo "This not a  page" |sudo tee /var/www/html/custom_404.html

SERVER=$(hostname)

SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
		add_header X-Served-By '$SERVER';
                try_files \$uri \$uri/ =404;
        }
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

sudo /etc/init.d/nginx restart
