#!/bin/bash
# This script displays listening ports with the PID and name of the program
# It uses netstat with the following options:
# -t - Show TCP ports
# -u - Show UDP ports
# -n - Show numerical addresses instead of resolving hosts
# -l - Show only listening ports
# -p - Show the PID and name of the listener's process
# This information is shown only if you run the script as root or sudo user

netstat -tunlp
#netstat -tp

