#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80

#creates a symbolic link(-a option) between the nginx configuration file
ln -sf /etc/nginx/sites-available/default  /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
#terminate any running nginx process
kill "$(pgrep 'nginx' | head -1)"
