#!/usr/bin/env bash

# server nginx

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Use IP of server as domain name
    server_name 3.90.65.243

    # Customize HTTP response header
    add_header X-Served-By 184122-web-01;

    # Server /airbnb-onepage/ route on AirBnB_clone_v2
    location = /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
    }

    error_page 404 /404.html
    location /404 {
      root /var/www/html;
      internal;
    }
}
